manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/MangoIV
  projects:
    - name: zmk
      remote: MangoIV
      revision: zephyr-2.5-lvgl-theme-fixes
      import: app/west.yml
  self:
    path: config
